version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=local
    ports:
      - "8080:8080"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - .:/usr/src

  app-test:
    build:
      context: .
      args:
        - ENVIRONMENT=test
#    entrypoint: [ "pytest", "test" ]
    volumes:
      - .:/usr/src


